-- Verificar estructura de tablas
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'crm_spa_medico' AND TABLE_NAME = 'products'
ORDER BY ORDINAL_POSITION;

SELECT '---' AS separator;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'crm_spa_medico' AND TABLE_NAME = 'patients'
ORDER BY ORDINAL_POSITION;

SELECT '---' AS separator;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'crm_spa_medico' AND TABLE_NAME = 'users'
ORDER BY ORDINAL_POSITION;
